### ISSUE TITLE
indexfold update

### ISSUE THREAD

**Issue by ThomasArts** [Quviq/leveled#10]
If we provide an IndexSpec of [{add, dep, 1}] to a specific key in a specific bucket and then overwrite with the same bucket and same key, but a different IndexSpec, viz [], then the previous IndexSpec is preserved. I interpret this as that IndexSpecs are updated according to the principle as joining the new spec with the old. If there is an `add` operation it is added, it there is a `remove` it is removed.

Is that meant to be so? It seems to work that way.

**Comment by russelldb** [comment]
That's correct. And very much like the question on deleting objects but the index remaining. Essentially indexes are just keys in the ledger, like any other. The tag just means they're grouped together, separate from object keys. Managing the relationship/integrity of indexes and objects is entirely the purview of the application. The API allows the index updates and object updates to be atomic by providing arguments for both.
