### ISSUE TITLE
Arbitrary fold functions in indexfold

### ISSUE THREAD

**Issue by ThomasArts** [Quviq/leveled#14]
This is one of the more confusing things, the user provides a weird fold function to indexfold:
```
fun(<<98, 117, 99, 107, 101, 116, 50>>,
    {4,
     <<81, 123, 207, 191, 210, 220, 49, 254, 255, 121, 189, 250, 9,
       66, 204, 140>>},
    []) ->
     [0];
   (_, _, _) -> [] end
```
In other words for bucket `<<"bucket2">>` and key `{4, <<81, 123, ...>>}` (which is arguably an illegal key, it returns [0] is the accumulator is [] otherwise it always returns [].

With this weird fold function we get:
```
leveled_eqc:init_backend(o_rkv, [{root_path, Dir}, {cache_size, 2048}]) -> <0.12848.0>
leveled_eqc:put(<0.12848.0>, <<98, 117, 99, 107, 101, 116, 50>>,
    <<81, 123, 207, 191, 210, 220, 49, 254, 255, 121, 189, 250, 9,
      66, 204, 140>>,
    <<53, 1, 0, 0, 0, 18, 131, 108, 0, 0, 0, 1, 104, 2, 100, 0, 4,
      100, 97, 118, 101, 97, 1, 106, 0, 0, 0, 1, 0, 0, 0, 33, 1, 91,
      171, 234, 119, 74, 136, 4, 227, 121, 110, 105, 133, 7, 206, 115,
      102, 149, 19, 191, 57, 60, 51, 230, 68, 51, 4, 207, 250, 69, 154,
      0, 163, 0, 0, 0, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 101,
      0>>,
    [{add, dep, 2}], o_rkv) ->
  ok
leveled_eqc:put(<0.12848.0>, <<98, 117, 99, 107, 101, 116, 50>>,
    <<81, 123, 207, 191, 210, 220, 49, 254, 255, 121, 189, 250, 9,
      66, 204, 140>>,
    <<53, 1, 0, 0, 0, 57, 131, 108, 0, 0, 0, 4, 104, 2, 100, 0, 6,
      103, 101, 111, 114, 103, 101, 97, 1, 104, 2, 100, 0, 5, 105, 115,
      97, 97, 99, 97, 2, 104, 2, 100, 0, 5, 104, 97, 114, 114, 121, 97,
      3, 104, 2, 100, 0, 6, 98, 101, 114, 116, 105, 101, 97, 4, 106, 0,
      0, 0, 1, 0, 0, 0, 33, 1, 162, 232, 176, 101, 230, 234, 196, 223,
      12, 23, 2, 152, 49, 15, 20, 12, 132, 212, 179, 189, 243, 200,
      217, 26, 73, 112, 120, 222, 101, 14, 102, 218, 0, 0, 0, 15, 0, 0,
      0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 101, 0>>,
    [{add, dep, 4}], o_rkv) ->
  ok
leveled_eqc:indexfold(<0.12848.0>,
    {<<98, 117, 99, 107, 101, 116, 50>>,
     <<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0>>},
    {#Fun<eqc_fun.29.3766061>, []}, {dep, 2, 4}, {true, undefined},
    9) ->
  #Fun<leveled_runner.4.80344816>
leveled_eqc:fold_run(9, #Fun<leveled_runner.4.80344816>) -> [0]
```

Whereas the model expects the empty list. This again may be a fact that the order in which things are processes is reversed.

**Comment by ThomasArts** [comment]
The key provided is a tuple `{Index, Key}`, which (since `ReturnTerms == true`) is correct.

**Comment by russelldb** [comment]
Your query is the range `{dep,2, 4}`. Wouldn't you expect foldfun to be called with `4` after `2 and the result to be `[0]`?

**Comment by ThomasArts** [comment]
From slack: It is about the continuation...in riak that would contain the last result from a query, a pair, index-value and riak object key, that tells the next time the query is run to move the range up to the index-value in the continuation, and to only return primary keys greater than the riak-object-key
so in the model, you'd need three keys X and Y and Z, all with index field `dep` and value `4` and if your start key was Y then you should only get Z, if your start key was X you should get Y and Z

**Comment by ThomasArts** [comment]
Solution: out of scope for the moment.

**Comment by ThomasArts** [comment]
Solved this. If we look at the resulting index list as a sorted entity, it all falls in place!
