### ISSUE TITLE
Error badarg caught when safe reading a file to length ...

### ISSUE THREAD

**Issue by ThomasArts** [Quviq/leveled#18]
I have a reproducible counter example for this error message:
`2018-09-27T11:21:55.885 CDB20 <0.1878.0> Error badarg caught when safe reading a file to length 0`

The test case consistently producing this log message is:
```
leveled_eqc:init_backend(o,
    [{root_path, Dir}, {compression_point, on_compact},
     {max_journalsize, 1000}, {cache_size, 2060}],
    sut) ->
  <0.1866.0>
leveled_eqc:put(<0.1866.0>, <<98, 117, 99, 107, 101, 116, 51>>,
    <<38, 50, 201, 47, 167, 125, 57, 232, 84, 38, 14, 114, 24, 62,
      12, 74>>,
    <<87, 150, 217, 230, 4, 81, 170, 68, 181, 224, 60, 232, 4, 74,
      159, 12, 156, 56, 194, 181, 18, 158, 195, 207, 106, 191, 80, 111,
      100, 81, 252, 248>>,
    [], none) ->
  ok
leveled_eqc:put(<0.1866.0>, <<98, 117, 99, 107, 101, 116, 51>>,
    <<38, 50, 201, 47, 167, 125, 57, 232, 84, 38, 14, 114, 24, 62,
      12, 74>>,
    <<86, 201, 253, 149, 213, 10, 32, 166, 33, 136, 42, 79, 103, 250,
      139, 95, 42, 143, 161, 3, 185, 74, 149, 226, 232, 214, 183, 64,
      69, 56, 167, 78>>,
    [], none) ->
  ok
leveled_eqc:kill(<0.1866.0>) -> ok
leveled_eqc:init_backend(o,
    [{root_path, Dir}, {compression_point, on_compact},
     {max_journalsize, 1000}, {cache_size, 2060}],
    sut) ->
  error
```

**Comment by ThomasArts** [comment]
Branch created: https://github.com/Quviq/leveled/tree/bug-issue-18
Note that I crash the log process when the log message is created in order to shrink reliably.

**Comment by martinsumner** [comment]
Does the backend fail to start when you get this error message?  Are there any other errors thrown (this error isn't necessarily in itself a problem as it indicates that something can't be read as it got corrupted during writing - which may happen if a process got killed before it managed to write).

**Comment by martinsumner** [comment]
I have a little unit test in leveled_cdb which captures what might be a related problem:

```

badly_written_test() ->
    F1 = "../test/badfirstwrite_test.pnd",
    file:delete(F1),
    {ok, Handle} = file:open(F1, ?WRITE_OPS),
    ok = file:pwrite(Handle, 256 * ?DWORD_SIZE, <<1:8/integer>>),
    ok = file:close(Handle),
    {ok, P1} = cdb_open_writer(F1, #cdb_options{binary_mode=false}),
    ok = cdb_put(P1, "Key100", "Value100"),
    ?assertMatch({"Key100", "Value100"}, cdb_get(P1, "Key100")),
    ok = cdb_close(P1),
    {ok, P2} = cdb_open_writer(F1, #cdb_options{binary_mode=false}),
    ?assertMatch({"Key100", "Value100"}, cdb_get(P2, "Key100")),
    ok = cdb_close(P2),
    file:delete(F1).
```

If a write is incomplete, hanging at the end of the file.  When the file is reopened it skipped over the incomplete write, but then started writing after it.  Subsequent attempts to read anything new written to that file would fail after it is re-opened.

Just completing testing of the fix for this.

**Comment by martinsumner** [comment]
The bug I referred to above is now resolved in `master`.

As part of the change I also reduced the level of the log `CDB20` from error to warn - to indicate that the system should keep running despite the issue being detected.

**Comment by ThomasArts** [comment]
Yes, I can confirm that CDB20 is not seen any more, (I only look for critical errors in test).
