### ISSUE TITLE
Parameter cache_size

### ISSUE THREAD

**Issue by ThomasArts** [Quviq/leveled#5]
The cache_size parameter supplied as option to `leveled_bookie:book_start(Options)` cannot be less than 4!

The code in `leveled_bookie.erl` reads like:
```
            CacheJitter = 
                proplists:get_value(cache_size, Opts) 
                    div (100 div ?CACHE_SIZE_JITTER),
            CacheSize = 
                proplists:get_value(cache_size, Opts)
                    + erlang:phash2(self()) rem CacheJitter,
```
Since `CASHE_SIZE_JITTER`is hard coded 25, we `div` the provided cache size by 4.
This is fine, but results for cache size 0, 1, 2, and 3 in `CacheJitter`to be zero. The next line divides by zero in that case. 

Either clearly document this minimum cache size or improve the computation to be never dividing by zero. (A cache size of 0 may be conceptually perfectly fine as "no cache").

**Comment by martinsumner** [comment]
https://github.com/martinsumner/leveled/pull/170

**Comment by russelldb** [comment]
@ThomasArts does martin's latest merge to master from the above pr solve the issue? Can I close this?

**Comment by ThomasArts** [comment]
Solved!
