### ISSUE TITLE
forgotten start option root_path results in 'undefined' directory

### ISSUE THREAD

**Issue by ThomasArts** [Quviq/leveled#6]
When starting `leveled_bookie` without the start option `root_path`, the data will be written in a directory called 'undefined'. Probably it is more user friendly to fail to start and provided an error message.

**Comment by martinsumner** [comment]
https://github.com/martinsumner/leveled/pull/172 - this should now error/terminate on startup if the root_path is undefined

**Comment by ThomasArts** [comment]
verified!
